spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3307/weblove?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
openrouter.api.key=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